name: deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: cp .build/index.html .build/404.html
      - uses: crazy-max/ghaction-github-pages
        with:
          target_branch: gh-pages
          build_dir: .build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_GH_PAGES }}
